WIP - Add initial srp command
no-vacancies/novac-bot pull request #6
Opened 2018-09-21 09:54 UTC by Mav986

Argument validation is very barebones and can be improved on a lot.

2018-10-03 07:29 UTC, lukasni requested changes

2018-10-03 07:29 UTC, lukasni commented on Corp/controller.py
> +from Corp._config import SRP_URL, SRP_URL_WITH_COMMENT, LOSS_FORMAT
Should add example `SRP_URL_WITH_COMMENT` to `_config.dist.py`

2018-10-03 07:29 UTC, lukasni commented on Corp/_config.dist.py
> +SRP_USAGE = 'The commas are important!\nUsage: *!srp [exact pilot name to receive srp], [zkill lossmail url], ' \
This file should be split out into a private `_config.py` for `SRP_URL` and `SRP_URL_WITH_COMMENT` and a public `config.py` with the data that is save to commit publicly.

2018-10-03 07:29 UTC, lukasni commented on Corp/controller.py
> +from Corp._config import SRP_URL, SRP_URL_WITH_COMMENT, LOSS_FORMAT
`LOSS_FORMAT` also isn't defined, is that the same as `ZKILL_FORMAT`?

2018-10-03 07:29 UTC, lukasni commented on Corp/_config.dist.py
> +SRP_URL = 'SRP FORMRESPONSE URL HERE'
This could use a comment on how the URL should be formatted and ideally how to get the URL from google apps.

2018-10-06 03:39 UTC, Mav986 commented
Added user parameter to all command functions and updated the SRP command to log the submitting user.

The SRP command is the only one utilizing it right now, but it opens the door for more detailed logging and tracking command abuse.

2018-11-29 10:59 UTC, lukasni approved these changes

2018-11-29 11:13 UTC, merged